<div class="text-justify">
    <p>Ao se cadastrar no MyCook, você <strong>ESTÁ DE ACORDO COM OS TERMOS E CONDIÇÕES</strong> a plataforma. Note que a recusa destes Termos, você ficará impedido de solicitar pedidos, quanto para se candidatar como fornecedor na plataforma.</p>
    <h6><strong>1. SERVIÇOS OFERECIDOS</strong></h6>
    <p>1.1 O site MyCook tem por finalidade viabilizar e intermediar a relação entre:</p>
    <p>(i.1) pessoas físicas ou jurídica, chamado de <strong>fornecedor</strong>, que tenham competência e experiência na produção e entrega de produtos alimentícios com a qualidade e tenham disponibilidade para preparar e comercializar estes produtos para o consumo, do cliente final. </p>
    <p>(i.2) pessoas físicas ou jurídicas, chamado de <strong>cliente final</strong>, que tenham interesse em adquirir os produtos alimentícios comercializados pelos fornecedores para consumo próprio.</p>
    <p>1.2 Este termo se aplica para regular o uso do serviço oferecido pelo MyCook ao cliente final, possibilitando a escolha dos fornecedores cadastrados na plataforma, efetivar a aquisição dos produtos alimentícios fornecidos por estes fornecedores (e entrega em domicílio e retirada no local) de acordo com os produtos disponibilizado, sendo possível, igualmente, ao cliente final, a efetivação do pagamento dos produtos adquiridos e taxa de entrega, via on-line. Este termo também se aplica para o uso do serviço oferecido pelo MyCook ao fornecedor, possibilitando que o mesmo consiga incluir os seus produtos alimentícios na plataforma, da forma correta, realizando com isso a venda destes produtos para o cliente final, obedecendo todos os critérios de boas práticas definidos pela MyCook.</p>
    <p>1.3 O MyCook tem como objetivo, portanto, conectar através da nossa plataforma os clientes finais, com os fornecedores de produtos alimentícios cadastrados, possibilitando que o cliente final, solicite ao(s) fornecedor (es) pedidos de entrega de produtos alimentícios.</p>
    <p>1.4 Desde logo fica esclarecido ao cliente final, o qual se declara ciente, que o serviço oferecido pelo MyCook se relaciona único e exclusivamente na intermediação (com opção de pagamento on-line) para comercialização de produtos alimentícios, não envolvendo preparo, embalagem, disponibilização e entrega física (motoboy ou outros meios) destes produtos, sendo estes itens de inteira responsabilidade do fornecedor e da empresa responsável pela entrega física destes produtos, a quem deverão ser direcionados quaisquer reclamações acerca de problema decorrentes de vício, defeito e/ou inexecução da feitura, preparo e entrega. </p>
    <h6><strong>2. CADASTRO</strong></h6>
    <p>2.1 O cliente final e fornecedor, para utilizar os serviços acima descritos, deverão  necessariamente, realizar o cadastro dos dados solicitados na plataforma, assumindo integralmente a responsabilidade (inclusive cível e criminal) pela exatidão e veracidade das informações fornecidas no cadastro, que poderá ser verificada, a qualquer momento, pelo MyCook. </p>
    <p>(i.1) Em caso de informações incorretas, inverídicas ou não confirmadas, como também da negativa em corrigi-las ou enviar documentação que comprove a correção, a MyCook se reserva o direito de não concluir o cadastramento em curso ou, ainda, de bloquear o cadastro já existente, impedindo tanto o cliente final quanto o fornecedor de utilizar os serviços da plataforma até que, a critério do MyCook, a situação de anomalia esteja regularizada. O MyCook se reserva o direito de impedir, a seu critério, novos cadastro de novos cadastros, tanto de fornecedores quanto de clientes finais. </p>
    <p>2.2 Efetuado, com sucesso, o cadastro, tanto do cliente final quanto o fornecedor, terão acesso aos serviços por meio de login e senha, dados esses que se compromete a não divulgar a terceiros, ficando sob sua exclusiva responsabilidade qualquer solicitação de serviço e/ou cadastro de produtos alimentícios na plataforma, que seja feita com o uso de login e senha de sua titularidade. </p>

    <h6><strong>3. OBRIGAÇÕES DO USUÁRIO</strong></h6>
    <p>3.1 Efetuado com sucesso o cadastro tanto o cliente final quanto o fornecedor, obrigam-se a não divulgar a terceiros login e senha de acesso, nem permitir o uso de tais informações por terceiros, responsabilizando-se pelas consequências do uso de login e senha de sua titularidade. </p>
    <p>3.2 É obrigação do cliente final e fornecedor, disponibilizarem informações cadastrais totalmente verídicas e exatas, responsabilizando-se exclusiva e integralmente por todo o conteúdo por si informado no cadastro, mantendo atualizado e confirmado o endereço para entrega dos produtos encomendados e também o endereço do fornecedor para a retirada dos produtos alimentícios a ser comercializados. </p>
    <p>3.3 O cliente final e fornecedores que sejam menor de 18 anos de idade estão  cientes de que não poderão encomendar e adquirir (cliente final) e vender produtos alimentícios (fornecedor), em qualquer hipótese, produtos alcoólicos, responsabilizando-se pela correta informação de sua idade no momento do cadastro. </p>

    <h6><strong>4. OBRIGAÇÕES MyCook </strong></h6>
    <p>4.1 Disponibilizar a plataforma, com condições de uso que permitam para o cliente final, devidamente cadastrados, efetivar pedidos de compra anunciados e comercializados e meios de pagamento com o preço dos produtos e taxa de entrega e para os fornecedores, condições para que o seus produtos possam ser comercializados corretamente.</p>
    <p>4.2 Proteger, a confidencialidade de todas as informações e cadastros relativos tanto pelo cliente final quanto pelos fornecedores, assim como todas às operações financeiras realizadas, dos serviços previstos no presente termo. Contudo, não responderá pela reparação de prejuízos que possam ser derivados de apreensão e cooptação de dados por parte de terceiros que, rompendo os sistemas de segurança, consigam acessar essas informações. </p>

    <h6><strong>MODIFICAÇÕES DESTE TERMO</strong></h6>
    <p>5.1 O presente termos de uso poderá, a qualquer tempo, ter seu conteúdo, ou parte dele, modificados para adequações e inserções, tudo com vistas ao aprimoramento dos serviços disponibilizados.</p>
    <p>5.2 As novas condições entrarão em vigência assim que sua veiculada no site, sendo possível tanto ao cliente final quanto ao fornecedor manifestar oposição a quaisquer dos termos modificados, desde que o faça por escrito, através do nosso site, o que ira gerar o cancelamento de seu cadastro. </p>

    <h6><strong>ACEITAÇÃO DO TERMO DE USO</strong></h6>
    <p>6.1 O cliente final e/ou fornecedor declara ter lido, entendido e que aceita todas as regras, condições e obrigações estabelecidas no presente termo. </p>
</div>